{% set name = "Beaker" %}
{% set version = "1.11.0" %}
{% set sha256 = "ad5d1c05027ee3be3a482ea39f8cb70339b41e5d6ace0cb861382754076d187e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - funcsigs

test:
  imports:
    - beaker
    - beaker.crypto
    - beaker.ext

  requires:
    - coverage
    - mock
    - nose
    - pycrypto
    - sqlalchemy
    - webtest

about:
  home: https://beaker.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: 'A Session and Caching library with WSGI Middleware'
  description: |
    Beaker is a web session and general caching library that includes WSGI
    middleware for use in web applications.

    As a general caching library, Beaker can handle storing for various times
    any Python object that can be pickled with optional back-ends on a
    fine-grained basis.

    Beaker includes Cache and Session WSGI middleware to ease integration with
    WSGI capable frameworks, and is automatically used by Pylons and
    TurboGears.

  doc_url: http://beaker.groovie.org/
  dev_url: https://github.com/bbangert/beaker

extra:
  recipe-maintainers:
    - stuertz
