{% set name = "Beaker" %}
{% set version = "1.10.0" %}
{% set sha256 = "6072892918225f5a055413082f2ff285f3ebca6a3873a0d6e163253ba83f0450" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - funcsigs

test:
  imports:
    - beaker
    - beaker.crypto
    - beaker.ext

  requires:
    - coverage
    - mock
    - nose
    - pycrypto
    - sqlalchemy
    - webtest

about:
  home: https://beaker.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  summary: 'A Session and Caching library with WSGI Middleware'
  description: |
    Beaker is a web session and general caching library that includes WSGI
    middleware for use in web applications.

    As a general caching library, Beaker can handle storing for various times
    any Python object that can be pickled with optional back-ends on a
    fine-grained basis.

    Beaker includes Cache and Session WSGI middleware to ease integration with
    WSGI capable frameworks, and is automatically used by Pylons and
    TurboGears.

  doc_url: http://beaker.groovie.org/
  dev_url: https://github.com/bbangert/beaker

extra:
  recipe-maintainers:
    - stuertz
