travis:
  secure:
    BINSTAR_TOKEN: NmfutBJ9z4jA81etmMFl7s9BtYryf2F0lCTdnJgaKa7I/ysYwWH/eWLO/xGPWUKvAv1U6Y8hx5nH+SJsAjH43OHdr5Hf2eBWNqP7hfwvrNVYqMyIi08m3FhelhEngN4No1L68qKBsseWnFIZ04hwGmWxIX9U3StHCRDC+6ngzeLSZGGjNoI5W1s2w4Y6GwHxPPuGGc3eFyhySUIqPdDQcLnVHdMbY8jLNtlk6PYj9lL8HlzLC0SVAy37T7b6U+Pj7GvntwtUyq4nVi/pOM8fkggs4VqRN2jS7yPRhyoP5qYbQ6b+j7YDMtBjKSI568c0zouCZ0MSpDH3nDTEf/cCx8RoV9dkdThaKGKGCeN1KqYjJ3+68DSjbYyQPDef5RsbaGie4OajeerbbwxqukToV27SbX5eLVGQOxiaegh9/MuwHSKN2svZtLtduDcOySRJmuBnjPn6DKnYUVVQbrHk6s+9cqe55J3wo+ZXfua8NFRwwVI16Pgxeuo+Zg1O992vMsSxzCcJBm63K+ItIxfl/DvXV75uV2A2IkldWUgvQBISxR0Oqyfr0st2qAH3N3z34eDIrTi+rYZSnzz/Wn4DF134rLEraoQ/VR6egCACBWAPzjTObRuwJd4Bbxv4yflOQhsq5zPLNL7MOa13KTq5w7+XbQ+hmMU2iXjHPYDRack=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
