travis:
  secure:
    BINSTAR_TOKEN: mLULGdfzSANQqs/Nm5TEixzC1fR/diLKW9bBKM4672CehAoTB5jtVx1GurX12FrsF/0AR01ly+MJ+RDH2Wmn0enLWtkDvOEKTNsfPphC5yG/ogBjQp2xrZWmM2Zq+eR2h+rMOViA/bJRiSmSxDITsw2EmxzUGeIid6irlh4TDrGuOLi9omifIwH+ajrstJYgKCrw8ngP47Xf3BEGL1cOY1Ofg+IXsopdD0HB1PuRQI2beDu+Qz2bhizRaflzjtK55LZaQfZMihMhz8BmMXvce/Obj/fLkRHhjH26EVRfawBXD4f9iB+T+a17CVzuf7//ZoG0eThah40KkzFJzb1GDpuKfqUBKUdYq9IqbYx85CY7n8aHEYAKEyA+khUe6vN3Vfv8U4zGrX1CwVgUolN6MPIcW96o41DnKJaYFivZlK0HDRHNb/yOQe3aviceta70dVka58zLvm+RvmcxlpeQ/aFGlaQYYpKklZxwrImeSce/4ZBi7UyFxxe1AH1CvWuRGkTz/4DsddKf8U69hIbnRi1buJFF+gWtbBK0kOJxOowqsPf1PeatT4kJcMF8Q1ST/nVzxGqbtNK9tsArQhJ+exQDVsDWTHimqNREffsaSFJWodwBHr7j5ZeCL6upXMh6hDYObNnpmb08CK+4nGUIMlTw8TfR1H1BOT26xy/7DKo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
