travis:
  secure:
    BINSTAR_TOKEN: yk/mojEsQmaaG3Kf61J4L0LZnDlx0oO75cuHRXsOe3E3Fd3uHiQPeNeNkEvDLD+xCokdke0CkdoQuME+msl+4aroBKdSu8oZMsUnm8SVdtjlaAHTTjxuEizH31rrfmxFD9oFvhvBQx9syO94kXF9i+Zx6dEg89GRdwXLV33p9bKN4IVlS665+IHDyXnzp6nGBKNjeV1RlTLZQEMk2e4z7vxdtsREVfmJmos6LjYVEfs5LarekmkdjXt6VeDeAJdJHkYowh+b9JYbWhPnj8em5D3ETHJwa+DfjPufaDZdbCRmP/lOL2NUQbyTUeqm6g6t1FoRcIxfzLxYBBgKrhaCKRpacVjKlcxENuwOw34yARqkDpngqt40Z3XeTv3fryIO69YufqxzCfGen/23rnzEcj/dBvP1z+al8JpixpytHUSGADep4UTW0DaoZAd6Nqx9eiHQ4KeZM5/9TtOAAeGbO1GNXqv+PtdXU9TFFgAH3nZZSB0wrhxRuMZaFhOOCFCKc+SYRcNQtfkiQH4GpCJpMjS4vSPxbjuW2IncrDBFy0/JawXMXMRc2XxGwgwSZQg2ZwasZgO3nkBAVmS2KALNibcCYFgwgYr4VINIuhqXGSyZ5rigmaoQV53+t9xqUAH7Fmsvvg43ykXXGzNkyVE9zGXVs7b8lud7MsM0iYT9CJU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
